# Generated by Django 4.0.5 on 2022-06-09 04:57

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screen', '0001_initial'),
        ('media', '0002_alter_media_dimension_alter_media_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=3, verbose_name='Status (Auto)')),
                ('date_option', models.CharField(choices=[('All Time', 'Alltime'), ('Custom', 'Custom')], max_length=10)),
                ('start_date', models.DateField(blank=True, verbose_name='Start Date (if Date Option is Custom)')),
                ('end_date', models.DateField(blank=True, verbose_name='End Date (if Date Option is Custom)')),
                ('day', multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56)),
                ('hour_option', models.CharField(choices=[('All Time', 'Alltime'), ('Custom', 'Custom')], max_length=10)),
                ('start_hour', models.TimeField(blank=True, verbose_name='Start Hour (if Hour Option is Custom)')),
                ('end_hour', models.TimeField(blank=True, verbose_name='End Hour (if Hour Option is Custom)')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.playlist')),
                ('televisions', models.ManyToManyField(to='screen.television')),
                ('videotrons', models.ManyToManyField(to='screen.videotron')),
            ],
        ),
    ]
