# Generated by Django 4.0.5 on 2022-06-09 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='End Date (if Date Option is Custom)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_hour',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='End Hour (if Hour Option is Custom)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date (if Date Option is Custom)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Start Hour (if Hour Option is Custom)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off')], default='Off', max_length=3, verbose_name='Status (Auto)'),
        ),
    ]
