# Generated by Django 4.0.5 on 2022-06-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Videotron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='videotron_img')),
                ('width', models.IntegerField(verbose_name='Width (in m)')),
                ('height', models.IntegerField(verbose_name='Height (in m)')),
                ('resolution', models.CharField(choices=[('16:9', 'Widescreen 1920X1080'), ('16:9_2', 'Widescreen1 1920X1080'), ('16:9_3', 'Widescreen2 1920X1080'), ('16:9_4', 'Widescreen3 1920X1080')], max_length=100)),
                ('address', models.TextField()),
                ('monetization_status', models.IntegerField(choices=[(1, 'On'), (2, 'Off')], default='2')),
                ('monetization_price', models.IntegerField(verbose_name='Monetization Price (per 15s)')),
            ],
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='television_img')),
                ('size', models.CharField(choices=[('1', '40 Inches'), ('2', '41 Inches'), ('3', '42 Inches'), ('4', '43 Inches')], max_length=100)),
                ('resolution', models.CharField(choices=[('16:9', 'Widescreen 1920X1080'), ('16:9_2', 'Widescreen1 1920X1080'), ('16:9_3', 'Widescreen2 1920X1080'), ('16:9_4', 'Widescreen3 1920X1080')], max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('monetization_status', models.IntegerField(choices=[(1, 'On'), (2, 'Off')], default='2')),
                ('monetization_price', models.IntegerField(verbose_name='Monetization Price (per 15s)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.branch')),
            ],
        ),
    ]
