# Generated by Django 4.0.5 on 2022-06-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('1', 'admin'), ('2', 'user'), ('3', 'store_owner')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='Store Name')),
                ('phone_number', models.CharField(max_length=13)),
                ('logo', models.ImageField(blank=True, upload_to='store/logo')),
                ('industry', models.CharField(choices=[('F&B', 'Food Beverage'), ('E-Commerce', 'E Commerce'), ('Advertisement', 'Advertisement')], max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=16)),
                ('store_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
