# Generated by Django 4.0.5 on 2022-06-09 06:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_payout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='user',
        ),
        migrations.AddField(
            model_name='payout',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.store'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
