# Generated by Django 4.0.5 on 2022-06-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dimension (Auto)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Duration in seconds (Auto)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='size',
            field=models.CharField(blank=True, max_length=100, verbose_name='Size (Auto)'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Length in seconds (Auto)'),
        ),
    ]
